## 张量
+ 张量和数组、矩阵一样，是一种特殊的数据结构，在pytorch中，神经网络的输入、输出以及网络参数都是用张量进行描述的。
+ 张量和np.ndarrays很类似，区别在于张量可以在GPU或者其他专用硬件熵运行，获得加速效果。
### 张量初始化效果
1. 直接生成：`torch.tensor([1,2])`
2. numpy生成：`x_np = torch.from_numpy(np_array)`，反过来，使用张量生成numpy数组也可。（即可以相互转换)
3. 通过已有张量生成，新的张量继承已有张量的数据属性（结构、类型），也可以重新指定：`x_ones = torch.ones_like(x_data)`、`x_rand = torch.randd_like(x_data,dtype=torch.float)`
4. 指定数据维度来生成张量（实例见下一个cell）。
   
### 张量属性
+ 从张量属性可以得到张量的维数、数据类型以及他们所存储的设备（CPU或者GPU）
  
### 张量运算
+ 有超过100种的张量运算方式，例如转置、索引、切片、数学运算、线性代数、随机采样等。
+ 所有这些运算都可以在GPU上运行。判断当前环境GPU是否可用：`if torch.cuda.is_available()：tensor = tensor.to('cuda)`

### 张量与numpy之间转化
+ 张量和numpy array数组在cpu上可以共用一块内存区域，改变其中一个，另一个也会随之改变。
   

In [3]:
import numpy as np
import torch

# 指定数据维度来生成张量
shape = (2,3,) # 元组
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor:\n {rand_tensor} \n')

Random Tensor:
 tensor([[0.7225, 0.1703, 0.0274],
        [0.5735, 0.0462, 0.3702]]) 



In [8]:
# 张量的运算

# 索引和切片
tensor = torch.ones(4,4)
tensor[:,1] = 0
print('tensor:',tensor)

# 张量拼接:torch.cat()、torch.stack()等
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print('t1:',t1)

# 张量的乘积和矩阵乘法
mul_1 = tensor.mul(tensor)
print(f'逐个元素相乘结果：{mul_1}\n')
mul_2 = tensor*tensor
print(f'逐个元素相乘等价写法结果：{mul_2}\n')

mul_3 = tensor.matmul(tensor.T)
print(f'矩阵乘法，tensor乘以tensor的转置：{mul_3}\n')
mul_4 = tensor @ tensor
print(f'矩阵乘法的等价写法结果：{mul_4}\n')

tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
t1: tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
逐个元素相乘结果：tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

逐个元素相乘等价写法结果：tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

矩阵乘法，tensor乘以tensor的转置：tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

矩阵乘法的等价写法结果：tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])



In [9]:
# 自动赋值运算
# 自动赋值运算通常在方法后有_作为后缀，
# 例如：x.copy_(y)操作会改变x的取值

print(tensor,'\n')
tensor.add_(5)
print(tensor)

# 注意：自动赋值运算虽然可以节省内存，但是在求导的过程中由于丢失了中间过程而导致一些问题，不鼓励使用。

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [14]:
# 张量转为numpy array
t = torch.ones(5)
print(f'张量t:{t}\n')
n = t.numpy()
print(f'array n:{n}\n')

# 修改张量的值，则array的值也随之改变。（最前面的概念，它俩可以用一块内存在cpu上）
t[0] = 100
print(t)
print(n)

# 由array 转化为tensor
m = np.ones(5)
print(f'array m:{m}\n')
t_m = torch.from_numpy(m)
print(f'张量t_m:{t_m}\n')

# 修改数组的值，张量的值也会随之改变
m[2] = 99
print(m)
print(t_m)

张量t:tensor([1., 1., 1., 1., 1.])

array n:[1. 1. 1. 1. 1.]

tensor([100.,   1.,   1.,   1.,   1.])
[100.   1.   1.   1.   1.]
array m:[1. 1. 1. 1. 1.]

张量t_m:tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

[ 1.  1. 99.  1.  1.]
tensor([ 1.,  1., 99.,  1.,  1.], dtype=torch.float64)
